# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: Linux
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: Build
    steps:
    - task: Rust@1
      inputs:
        installNightly: false
    - task: Cargo@1
      inputs:
        cargoCommand: 'build'
        cargoCommandOptions: '--color=always --all --all-targets'
        verbose: false

- stage: Windows
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: Build
    steps:
    - task: Rust@1
      inputs:
        installNightly: false
    - task: Cargo@1
      inputs:
        cargoCommand: 'build'
        cargoCommandOptions: '--color=always --all --all-targets'
        verbose: false

